# Generated by Django 5.1 on 2024-10-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_post_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.TextField(max_length=5000)),
                ('habitat', models.TextField()),
                ('diet', models.TextField()),
                ('conservationstatus', models.CharField(max_length=50)),
            ],
        ),
    ]
